### ISSUE TITLE
Support for bar chart types?

### ISSUE THREAD

**Issue by koriner** [bellstrand/highcharts-border-radius#2]
Thanks for your plugin - works well for columns but it doesn't support the bar type charts.

Any chance you would consider adding support for bars as well?

Cheers :)

**Comment by bellstrand** [comment]
Hi @koriner,

I haven't used highcharts for over a year now, and have no active project with it in sight.
So It's unlikely that I'll take the time to expand this plugin in the near future.

But I'll keep it in mind, and contributions are always welcome!

**Comment by prajapatisagar4288** [comment]
Great Work. I wasted my whole day for this thing and finally i got your NPM library link and it worked. Thanks man

**Comment by saptarshimazumdar** [comment]
@koriner, I know I'm late. But this may help others who're facing similar issues.  It's compatible with bar charts too.

```Javascript
plotOptions: {
        bar: {
            borderRadiusTopLeft: 5,
	    borderRadiusTopRight: 5
        }
    }
```
For a complete code you may [visit here](https://jsfiddle.net/6xzg1uLy/)

**Comment by bellstrand** [comment]
As Bluff-0 says, bar charts have always worked.
I've added some examples to the readme and in a /examples directory where you can find them for the future.
Closing this issue.
