### ISSUE TITLE
Readme Update

### ISSUE THREAD

**Issue by robertoandres24** [bellstrand/highcharts-border-radius#3]
if the project is built on top of a stack of like webpack it is necessary to call the plugin in this way.
this works for me:
```
 var borderRadius = require('highcharts-border-radius');
 borderRadius(Highcharts);
```
by the way, thanks for the nice plugin

**Comment by bellstrand** [comment]
It was a while ago that I've used Highcharts now, so haven't stumbled on it. But I've updated the README with those 2 lines.
