### ISSUE TITLE
Web Compatibility

### ISSUE THREAD

**Issue by saptarshimazumdar** [bellstrand/highcharts-border-radius#5]
Hey Magnus Bellstrand,

I used this module today for the web by changing a few lines of code and I thought developers can access this library for basic web purposes too. I can modify a few lines of code for you to make it web-compatible via CDN. Since it's your project, I may pull a request and add a file here.

**Comment by bellstrand** [comment]
Go for it!
I haven't used the library myself for a couple of years, but I'll happily merge in any improvement.

**Comment by saptarshimazumdar** [comment]
[Patch-1](https://github.com/Bluff-0/highcharts-border-radius/tree/patch-1)
[Patch-2](https://github.com/Bluff-0/highcharts-border-radius/tree/patch-2)
[Patch-3](https://github.com/Bluff-0/highcharts-border-radius/tree/patch-3)

I've made these three patches. You may merge these pull requests. 💯
