### ISSUE TITLE
Includes arrow function that breaks IE11

### ISSUE THREAD

**Issue by sethomas** [bellstrand/highcharts-border-radius#7]
https://github.com/bellstrand/highcharts-border-radius/commit/d04425b4765efb61acea010f530c895aa8f02c14#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R17

As we do not compile `node_modules` directory, this is now breaking our application in IE11 due to arrow function.

**Comment by bellstrand** [comment]
@sethomas Sorry for that, haven't used the library myself for a couple of years so won't put the time in to fix a CI workflow to guarantee IE11 support.
I've fixed your issue thou, and published it in `0.0.4`, hope that helps!
