### ISSUE TITLE
Negative values should have inverted values (top vs bottom)

### ISSUE THREAD

**Issue by alvarotrigo** [bellstrand/highcharts-border-radius#8]
I'm adding border radius on top left/right and when there are negative values on the chart this obviously have to get inverted too becoming bottom left/right in those cases.

See this picture:
![image](https://user-images.githubusercontent.com/1706326/115230313-763c1900-a114-11eb-8240-2ea995d2235a.png)

Any way to dynamically change the border radious position based on the point value?

**Comment by bellstrand** [comment]
@alvarotrigo That should probably be a simple fix.
But I haven't used this library for over 4 years, so won't make any effort to fix it myself.
I'd be happy to merge a contribution thou if you decide to fix it.

**Comment by alvarotrigo** [comment]
> But I haven't used this library for over 4 years, so won't make any effort to fix it myself.
> I'd be happy to merge a contribution thou if you decide to fix it.

Ups!

I thought this was the official one.
I guess I was confused with this one:
https://github.com/highcharts/rounded-corners

Sorry about that :)
